### ISSUE TITLE
On the ndc2pix matrix

### ISSUE THREAD

**Issue by hbb1** [Han230104/2D-Gaussian-Splatting-Reproduce#1]
Hi, Thank you for your great repo!  I am currently working on aligning 2DGS' camera to 3DGS, and I found your ndc2pix is particularly useful in this context. I found your ndc2pix can present some round-off error and made some modifications:

```C++
glm::mat4 Ndc2Pixel = glm::mat4(
	W/2,	        0,	       0,			        W/2,
	0,		H/2,	       0,				H/2,
	0,		0,	       far_n-near_n,	           near_n,
	0,		0,		0,				1 
);
```
My  modifications
```C++
glm::mat4 Ndc2Pixel = glm::mat4(
	float(W)/2.0,	        0.0,	       0.0,			        float(W-1)/2.0,
	0.0,		float(H)/2.0,	       0.0,				float(H-1)/2.0,
	0.0,		0.0,	       far_n-near_n,	           near_n,
	0.0,		0.0,		0.0,				1.0
);
```
First, I enforced the W, H to be float before division, otherwise odd number will be floored. 
Second, I found that the original ndc2pix should minus 0.5, so did I in the shift parameters.
```C++
__forceinline__ __device__ float ndc2Pix(float v, int S)
{
	return ((v + 1.0) * S - 1.0) * 0.5;
}
```
Here are my experiments on the NeRF synthetic chair (no regularizations imposed). 
I found it consistent  with my early experiments on pixel-alignment: https://github.com/hbb1/diff-surfel-rasterization/issues/3#issuecomment-1829639471:

| Exp              | PSNR | 
| :---------------- | :------: |
| half pixel        |   35.35   |
| wo /  half pixel           |   34.55   |

I am not sure if the gains are as pronounced as in other dataset. Just want to inform you my findings.

**Comment by Yanbing-Han** [comment]
Thank you for sharing ! I'll check it later. I am a little busy these days.
