### ISSUE TITLE
training much faster than origin 2dgs

### ISSUE THREAD

**Issue by cv-lab-x** [Han230104/2D-Gaussian-Splatting-Reproduce#2]
hi, thanks for your great work, why your reproduce version is much faster than origin 2dgs ? what did you do to improve efficiency? 
@Han230104  Looking forward to your reply, thanks
![image](https://github.com/Han230104/2D-Gaussian-Splatting-Reproduce/assets/26067407/1f98ed69-32af-4aef-a9d7-eec56bcfacf0)

**Comment by Yanbing-Han** [comment]
I think my improvement for efficiency can attribute to a simple modification for the prune strategy.
```
if iteration > opt.densify_from_iter and iteration % opt.densification_interval == 0:
                    size_threshold = 20 if iteration > opt.opacity_reset_interval else None
                    is_prune = True if iteration % opt.prune_interval == 0 else False
                    gaussians.densify_and_prune(opt.densify_grad_threshold, 0.2, scene.cameras_extent, size_threshold, is_prune)
```
I set prune_threshold = 0.2 and prune_interval = 1500

```
dL_dmean2D[idx].x = 4.0f * dL_dmeans[idx].x;
dL_dmean2D[idx].y = 4.0f * dL_dmeans[idx].y;
```
And I project the gradient in this way to keep a balance between efficiency and effectiveness.
