### ISSUE TITLE
the gradient of the projected 2D center

### ISSUE THREAD

**Issue by Yubel426** [Han230104/2D-Gaussian-Splatting-Reproduce#3]
```
dL_dmean2D[idx].x = 4.0f * dL_dmeans[idx].x;
dL_dmean2D[idx].y = 4.0f * dL_dmeans[idx].y;
```
Hi! Can you provide some explanation or insight about this calculation?

**Comment by Yanbing-Han** [comment]
This is just a hyperparameter that I get from experiment. When I first reproduce the 2dgs, the result isn't satisfactory, so I adjust this parameter to improve the results. 
I also change the Densification strategy to improve the efficiency.
```
if iteration > opt.densify_from_iter and iteration % opt.densification_interval == 0:
                    size_threshold = 20 if iteration > opt.opacity_reset_interval else None
                    is_prune = True if iteration % opt.prune_interval == 0 else False
                    gaussians.densify_and_prune(opt.densify_grad_threshold, 0.2, scene.cameras_extent, size_threshold, is_prune)
```
I set prune_threshold = 0.2 and prune_interval = 1500

**Comment by hbb1** [comment]
Hi, good job! Beside the hyperparameters, I just found your implemented rasterizer can also run faster! For example,  fusing the compuate_radius and compute_transformation togather can also improve speed, reducing the global memory access. Can I integrate some of your code into the official code  and then perform some tests. I will share my finding and give a reference link here. Thank you.

**Comment by Yanbing-Han** [comment]
Yes, feel free to integrate the code.
